### ISSUE TITLE
Fab 按钮异常       #Bug反馈# Nexus 5;6.0.1;V6.1.9; 

### ISSUE THREAD

**Issue by Jarvanh** [wangdan/AisenWeiBo#40]
点开 Fab 按钮，把应用切换到后台，再返回，Fab 按钮会出现异常。

![](http://i.imgur.com/ZszMqGV.png)

![](http://i.imgur.com/PRhZAvq.png)

**Comment by wangdan** [comment]
已经发现了，能越养越大，别人建议我不要修复了。。。我也养了一次，养到了最大，挂了。。。

**Comment by wangdan** [comment]
平常一些小细节基本不会再修复了，因为没时间。每次更新版本我都集中更新一两周，然后大部分的时间都在开发新功能上。所以每次集中更新的时候，变化都好大。。。
